apiVersion: v1
kind: Service
metadata:
  name: qcl-app
  namespace: istio-system
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 30051
      targetPort: grpc
      nodePort: 30051
  selector:
    app: qcl-app
  type: NodePort
