apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcl-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcl-app
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: qcl-app
    spec:
      containers:
        - name: qcl-app
          image: "docker.io/alesj/qcl-app:1.0.0-SNAPSHOT"
          ports:
            - name: grpc
              containerPort: 30051
              protocol: TCP
